{
 "title": "Traefik Officer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Quantile",
    "label": "Quantile",
    "query": "label_values(traefik_officer_latency_metrics, quantile)"
   },
   {
    "name": "RequestMethod",
    "label": "Request Method",
    "query": "label_values(traefik_officer_latency_metrics, RequestMethod)"
   },
   {
    "name": "RequestPath",
    "label": "Request Path",
    "query": "label_values(traefik_officer_latency_metrics, RequestPath)"
   },
   {
    "name": "TraefikInstance",
    "label": "Traefik Instance",
    "query": "label_values(traefik_officer_lines_processed, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Processed Per Router / Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_officer_latency_metrics_count{RequestMethod=~\"$RequestMethod\", RequestPath=~\"$RequestPath\"}",
     "legendFormat": "{{RequestMethod}} {{RequestPath}}"
    }
   ]
  },
  {
   "title": "Traefik Officer Requests Processed Total",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "traefik_officer_lines_processed{pod=~\"$TraefikInstance\"}",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Traefik Officer Requests Ignored",
   "type": "stat",
   "gridPos": { "h": 16, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "traefik_officer_lines_ignored{pod=~\"$TraefikInstance\"}",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Traefik Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "traefik_officer_latency_metrics{RequestMethod=~\"$RequestMethod\", RequestPath=~\"$RequestPath\", quantile=~\"$Quantile\", pod=~\"$TraefikInstance\"}",
     "legendFormat": "{{RequestMethod}} {{RequestPath}} {{quantile}}"
    }
   ]
  }
 ]
}